-- CRIACAO DO BANCO DE DADOS

CREATE DATABASE ESTUDOSBD;

-- CONECTANDO AO BANCO DE DADOS

USE ESTUDOSBD;

-- CRIANDO A TABELA 

CREATE TABLE CLIENTE (
	ID INT AUTO_INCREMENT PRIMARY KEY; 
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF VARCHAR(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
	);
	
--VERIFICANDO TABELA BEM COMO SUA DESCRICAO

DESC CLIENTE;
	
-- ALTERANDO TABELA CRIADA DEFININDO CAMPOS NAO NULOS E UNICOS

ALTER TABLE CLIENTE
MODIFY COLUMN NOME VARCHAR(30) NOT NULL,
MODIFY COLUMN SEXO CHAR(1) NOT NULL DEFAULT 'N',
MODIFY COLUMN EMAIL VARCHAR(30) NOT NULL UNIQUE,
MODIFY COLUMN CPF VARCHAR(11) NOT NULL UNIQUE,
MODIFY COLUMN TELEFONE VARCHAR(30) NOT NULL,
MODIFY COLUMN ENDERECO VARCHAR (100) NOT NULL

-- POPULANDO TABELA 

INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) 
VALUES ('RAFAEL',  'M',   'rafael@hotmail.com',  '456.909.789-15',  '(11) 91234-5678',  'AV. BRASIL, 500 - SÃO PAULO - SP'),
('João Silva', 'M', 'joao.silva@email.com', '123.456.789-00', '(11) 98765-4321', 'AV. PAULISTA, 1000 - SÃO PAULO - SP'),
('Maria Santos', 'F', 'maria.santos@email.com', '987.654.321-00', '(21) 97654-3210', 'RUA DO OUVIDOR, 50 - RIO DE JANEIRO - RJ'),
('Carlos Oliveira', 'M', 'carlos.oliveira@email.com', '456.789.123-00', '(31) 96543-2109', 'AV. AFONSO PENA, 2000 - BELO HORIZONTE - MG'),
('LILIAN', 'F', 'lilian@gmail.com', '098.765.432-01', '(27) 99876-7649', 'RUA DAS DORES - GLORIA - VILA VELHA - ES'),
('RAFAEL', 'M', 'rafael@hotmail.com', '123.456.789-10', '(11) 91234-5678', 'AV. BRASIL, 500 - SÃO PAULO - SP');

-- UTILIZANDO COMANDO SELECT // SERVE PARA REALIZAR PROJECAO 

SELECT NOW() AS DATA_HORA;

--CRIANDO ALIAS DE COLUNAS

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;  -- AS CLIENTE IRA SUBSTITUIR O TITULO DA COLUNA 'NOME' POR CLIENTE


SELECT EMAIL, SEXO, ENDERECO, NOME AS CLIENTE, NOW() AS DARA_HORA FROM CLIENTE; 

-- FILTRANDO A TABELA // WHERE == ONDE 

SELECT NOME, SEXO FROM CLIENTE   -- FILTRO NOME E SEXO ONDE SEXO SEJA IGUAL 'M'
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE  -- FILTRO NOME E ENDERECO DO SEXO FEMININO
WHERE SEXO = 'F';

SELECT NOME, CPF FROM CLIENTE;

UPDATE CLIENTE
SET CPF = '092.398.238-45'
WHERE NOME = 'RAFAEL'

-- LIKE QUER DIZER COMO E SUBSTITUI O SINAL DE IGUALDADE, ADD O PERCENT O COMANDO VAI IGNORAR E PROCURAR O QUE CONTÉM

SELECT NOME, SEXO FROM CLIENTE 
WHERE ENDERECO LIKE '%SP';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE '%SP';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE '%GLORIA%';

-- INSERINDO ID NA TABELA

ALTER TABLE CLIENTE
ADD COLUMN ID INT AUTO_INCREMENT PRIMARY KEY FIRST;